name: Deploy website
on:
  push:
    branches:
    - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
       - name: Download code
         uses: actions/checkout@v4
       - name: Install dependencies
         run: npm run ci
       - name: Run code linting
         run: npm run lint
       - name: Test the code
         run: npm run test
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Download code
        uses: actions/checkout@v4
      - name: install dependenvies
        run: npm run ci
      - name: Build the system
        run: npm run build
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist-files
          path: dist
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: dist-files
          path: dist
      
      

        
      
  
