name: Job Output
on:
    push:
        branches: [main]

jobs:
    jobs1:
        runs-on: ubuntu-latest
        outputs:
            example_output: ${{ steps.set_output.outputs.example }}
        steps:
            - name: job-output1
              id: job_output
              run: echo "name=ravikiranpadki" >> @GITHUB_OUTPUT

            - name: job-output2
              run: echo "age=30" >> $GITHUB_OUTPUT
              
    jobs2:
        needs: jobs1
        runs-on: ubuntu-latest
        steps:
            - name: access_outputjob
              run: |
                echo "Value of name is {{needs.jobs1.outputs.job_output1}}"
                echo "Value of age is {{needs.jobs1.outputs.job_output2}}"
    
