name: Step Output

on:
  push:
    branches: [main]

jobs:
  job1:
    runs-on: ubuntu-latest

    steps:
      - name: set output
        id: set_output
        shell: bash
        run: |
          echo "name=Ravikiran Padki" >> $GITHUB_OUTPUT
          echo "age=20" >> $GITHUB_OUTPUT

      - name: access output
        run: |
          echo "The name of the candidate is ${{ steps.set_output.outputs.name }}"
          echo "The value of age is ${{ steps.set_output.outputs.age }}"
