name: Step Output

on:
  push:
    branches: [main]

jobs:
  job1:
    runs-on: ubuntu-latest

    steps:
      - name: set output
        id: set_output
        shell: bash
        run: echo "Age = 20" >> $GITHUB_OUTPUT

      - name: access output
        run: echo ${{ steps.set_output.outputs.Age }}
