name: Step Output

on:
  push:
    branches: [main]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: set output 1
        id: set_output1
        shell: bash
        run: |
          echo "name=ravikiran" >> $GITHUB_OUTPUT
          echo "age=23" >> $GITHUB_OUTPUT

      - name: access output
        run: |
          echo "My name is - ${{steps.set_output1.outputs.name}}"
          echo "My age is - ${{steps.set_output1.outputs.age}}"
