name: Step Output

on:
  push:
    branches: [main]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: step-output1
        id: step_output1
        run: |
          echo "name=ravikiran" >> $GITHUB_OUTPUT
          echo: "age=29" >> $GITHUB_OUTPUT
      
      - name: step-output2
        id: step_output2
        run: echo "salary=3000" >> $GITHUB_OUTPUT

      - name: step-access
        run: |
          echo "My name is ${{ steps.step_output1.outputs.name }}"
          echo "My age is ${{ steps.step_output1.outputs.age }}"
          echo "My Salary is ${{ steps.step_output2.outputs.salary }}"
        
        
