name: Step Output

on:
  push:
    branches: [main]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: step-output
        id: step_output
        run: echo "name=ravikiran" >> $GITHUB_OUTPUT

      - name: step-access
        run: echo ${{ steps.step_output.outputs.name }}
